### ISSUE TITLE
Any chance to have this on bower ?

### ISSUE THREAD

**Issue by acourtiol** [fisharebest/font-awesome-rtl#1]
Your work is really great and it will be really useful to have it shared on bower.io :+1:

**Comment by fisharebest** [comment]
I am happy to do this, but I have never used bower.

I guess I must create bower.json

Can you help with this?

**Comment by acourtiol** [comment]
I'll make a PR in the afternoon for you :smiley:

**Comment by acourtiol** [comment]
Sorry I didn't had as much time as I expected last week. Here is a link to the bower tutorial that explain everything about publishing:
http://bower.io/docs/creating-packages/#bowerjson

**Comment by fisharebest** [comment]
I am still happy to do this.

I still have no experience with bower.
